version: '3'
services:
  web:
      image: nginx
      volumes:
        - ".:/app"
        - "./docker/nginx.conf:/etc/nginx/conf.d/default.conf"
      depends_on:
        - php
      ports:
      - "8000:80"
  php:
      image: php7.3-fpm-xdebug
      volumes:
        - ".:/app"
        - "./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini"
      depends_on:
        - db
  db:
      image: amd64/mariadb
      environment:
        MYSQL_ROOT_PASSWORD: root
      ports:
      - "3307:3306"